<?php

namespace Leart\JsonDerulo\Services;

use GuzzleHttp\Client;
use GuzzleHttp\Exception\GuzzleException;

/**
 * GeminiService — Plain REST + Guzzle
 *
 * Calls the Gemini generateContent endpoint using a minimal request body.
 * API key and model name are read from .env only — never hardcoded.
 *
 * First working version: plain text generation only.
 * No responseMimeType, responseSchema, or structured output configs.
 */
class GeminiService
{
    private Client $client;
    private string $apiKey;
    private string $model;

    /** Base URL without model or key — those are appended dynamically. */
    private string $baseUrl = 'https://generativelanguage.googleapis.com/v1/models/';

    public function __construct()
    {
        $this->apiKey = $_ENV['GEMINI_API_KEY'] ?? '';
        $this->model  = $_ENV['GEMINI_MODEL']   ?? 'gemini-1.5-flash';
        $this->client = new Client([
            'timeout'         => 90,
            'connect_timeout' => 15,
        ]);
    }

    /**
     * Build the full API endpoint URL.
     */
    private function buildUrl(): string
    {
        return $this->baseUrl . $this->model . ':generateContent?key=' . $this->apiKey;
    }

    /**
     * Generate a plain-text response from Gemini.
     *
     * Uses the minimal request shape:
     * { "contents": [{ "parts": [{ "text": "..." }] }] }
     *
     * Optionally prepends a system instruction and conversation history.
     *
     * @param string $prompt       The user's prompt
     * @param string $systemPrompt Optional system instruction
     * @param array  $history      Prior turns [{role, text}, ...]
     * @return array {success: true, text: string} | {error: true, message: string}
     */
    public function generate(string $prompt, string $systemPrompt = '', array $history = []): array
    {
        // ── Guard: API key must be set ──
        if (empty($this->apiKey) || $this->apiKey === 'YOUR_GEMINI_KEY') {
            return [
                'error'   => true,
                'message' => 'Gemini API key not configured. Add GEMINI_API_KEY to .env',
            ];
        }

        // ── Guard: prompt must not be empty ──
        if (empty(trim($prompt))) {
            return [
                'error'   => true,
                'message' => 'Prompt cannot be empty.',
            ];
        }

        // ── Build contents array ──
        $contents = [];

        // Add conversation history
        foreach ($history as $entry) {
            $role = ($entry['role'] === 'model' || $entry['role'] === 'assistant')
                ? 'model'
                : 'user';
            $contents[] = [
                'role'  => $role,
                'parts' => [['text' => $entry['text'] ?? $entry['message'] ?? '']],
            ];
        }

        // Add the current user prompt
        $contents[] = [
            'role'  => 'user',
            'parts' => [['text' => $prompt]],
        ];

        // ── Build request body — minimal shape ──
        $body = [
            'contents' => $contents,
        ];

        // System instruction (supported field in Gemini API v1)
        if (!empty($systemPrompt)) {
            $body['systemInstruction'] = [
                'parts' => [['text' => $systemPrompt]],
            ];
        }

        // ── Make the API call ──
        try {
            $response = $this->client->post($this->buildUrl(), [
                'json'    => $body,
                'headers' => ['Content-Type' => 'application/json'],
            ]);

            $data = json_decode($response->getBody()->getContents(), true);

            if (json_last_error() !== JSON_ERROR_NONE) {
                return ['error' => true, 'message' => 'Invalid JSON response from Gemini API.'];
            }

            // Extract the generated text
            $text = $data['candidates'][0]['content']['parts'][0]['text'] ?? null;

            if ($text !== null) {
                return ['success' => true, 'text' => $text];
            }

            // Check if the request was blocked
            $blockReason = $data['promptFeedback']['blockReason'] ?? null;
            if ($blockReason) {
                return ['error' => true, 'message' => "Request blocked by API: {$blockReason}"];
            }

            return ['error' => true, 'message' => 'No response generated by the model.'];

        } catch (GuzzleException $e) {
            $msg = $e->getMessage();
            // Never leak the API key in error messages
            $msg = str_replace($this->apiKey, '[REDACTED]', $msg);
            return ['error' => true, 'message' => 'Gemini API request failed: ' . $msg];
        }
    }

    /**
     * Generate a response and attempt to parse it as JSON.
     *
     * This does NOT use responseMimeType or responseSchema.
     * Instead, the system prompt instructs the model to reply in JSON,
     * and we parse the resulting plain text.
     *
     * @param string $prompt       User prompt (should describe the JSON you want)
     * @param string $systemPrompt System instruction (must ask for JSON output)
     * @return array {success: true, data: array} | {error: true, message: string}
     */
    public function generateJson(string $prompt, string $systemPrompt = ''): array
    {
        $result = $this->generate($prompt, $systemPrompt);

        if (isset($result['error'])) {
            return $result;
        }

        $text = $result['text'] ?? '';

        // Try to parse the full response as JSON
        $parsed = json_decode($text, true);
        if (json_last_error() === JSON_ERROR_NONE && $parsed !== null) {
            return ['success' => true, 'data' => $parsed];
        }

        // Fallback: extract JSON from a markdown code block
        if (preg_match('/```(?:json)?\s*([\s\S]*?)```/', $text, $m)) {
            $parsed = json_decode(trim($m[1]), true);
            if (json_last_error() === JSON_ERROR_NONE && $parsed !== null) {
                return ['success' => true, 'data' => $parsed];
            }
        }

        // Could not parse — return the raw text so the caller can display it
        return ['success' => true, 'data' => null, 'text' => $text];
    }
}
